language: c
compiler:
- gcc
before_script:
- mkdir build
- cd build
- cmake ..
- make
script: make
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: PBtz3kfNtUN9ebcVltGGBlazCK11Iik1gHWyL+DHDMQ+NqQXHFVUBQUPOs7G+DjtZAPCQbJtgRX7OnlIJ7RRRD/sx/jDd8ySnlUxsAJ2pp60IvIY+fovSXC+AW6MQzN7eUfhBdVxc4Y0TlaQ+5sB1MrMxg3LEP9kkyDmchk/wicEi+yTs2O8GY2/r/oDERbWsu/ufwH26EuO2zPAj3vfBWu3EwK9r21CYcdtAARwA8sRRvviflGLlBUHifDtR81zlkQdHh47FlBPOQsjvzZYYKswTpef44nlQCYGoapmc1/598YVSxPFypypzV2jSQOzpLLH1T2GJwAPaGAsfb2KKrLiqMs/b6Y01Eo5Xr0yPi8ULnO0DHI62QoVng1PWzAU9oUJCaMmhu2GBFSaOOKmoshKZVdlJVGTfO7HzQbk2zkKodmNUcPEs/TeCDKx5x+JjRNeFJ6FGSfco5uX4hn0nj2KXPnpzghx5bdA+NtpG+hvRzeL6VXPoUJEgIgGL0fZg6ajx8p24OWpdvDAAtfQzw9x9JTosVaSKDANblhPZlXSqHjYIf2i3e1HaxieM7tfhFcAGYZAxU2wyLVi42Ia4yovD/0zlguuDKPYXDCb16rkSj8ks0ELqLYANNCUah+y/v9ypwSrbrq5R8BUpp1sWCxJHudhzqEt1bVLh4HOug4=
  file: main
  on:
    repo: kevien/travisTest
