language: c

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: make
deploy:
  provider: releases
  api_key: 76e0830734ad457558862ca0da9ceca5230c9c59
  file: main
  skip_cleanup: true
  on:
    tags: true
