language: c
compiler:
- gcc
before_script:
- mkdir build
- cd build
- cmake ..
- make
script: make
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iHj1Qyj9JKbx/QZ8tLS4jf4SmZzh81CzS2NGPtIZrvbJVSx/fSiuZYKkLu/gMf2gEIlDVFh7RNgYRPapUS+ziP7H+y+ESBv8Wr051g3tvQ10N5Fe8qmbbBjmdRqH63v5urc49tStpUUUm4t8bnqoIb/RLG5HKGWqk3PHhE7N8+9KEl1uhQlnINlsexZ84zIpUWQmlJztc/GHXUNnWI5ixPhDHupafy8V4Oe+yzDtkr1RvxVV9V0EKLxYBw+Wb48l+nHNJ1Tg6nnLlYURCErNocauJsIJM5IgshZHWca/5XOwY0X1KE9Rdx86qZ9WzKUgfG3RkxLab2lqx0T5uGBWFtI0S5xHi+N3WKYOv7ra+MAqHvfLtN2e0jFpnCItunY1YGA4rOdpzyk/LisNbPpC5m6ajTI6eIvv3ieHWAwIWJsuwvMXaBvPU0absOrBnoXppOiJurD3hyY3CloHjO4MWA2Ie9MzAFEgSwiBHhGSni0WLY3yIkfR2LuSDQdoyo0Ip/0BiDP713t2296RPjhRAwGiSAqDyI91kZvnPMPccxYodoMUSfhWjUo3PNhm+GF3efoMI8w2E/Wn41HjXsyA9jDRYeYMGje00KmDxbuTAoVmot5hCAc6KGhSDEbX4Z6fUiCuyaAtVZUFZSqmnApN3MO+aG6yWix1XlxaJh1ur/k=
  file: sample
  on:
    repo: kevien/travisTest
